### ISSUE TITLE
Prevent reloading of graphics when not switching timescales

### ISSUE THREAD

**Issue by BruceJohnJennerLawso** [UW-Macrostrat/geo-timescale#1] opened 2015-06-04 20:27 UTC
Hi, just a minor something that I noticed that would be nice to fix. When clicking on the current time period (ie Phanerozoic in the demo view), the display text disappears while reloading similar to what happens when zooming in (ie clicking on carboniferous in the demo). I was wondering if it would be possible to add a check that avoids reloading in this way if the timescale is not zooming in or out?

Many thanks for this great project.

**Comment by jczaplew** [comment] 2015-06-04 20:52
This was something that I spent a bit of time deciding best how to handle. The issue is basically this:

Labels are placed based on the location (x,y) and size (width, height) of their parent interval. I found it was quite difficult (at the time) to sync the animation of both the interval boxes and labels such that they followed each other, and decided that it was best to just hide the labels, wait for the animation of the boxes to end, and then reposition the labels based on the new location/size of the boxes. 

I know that since this was created d3 has modified the handling of concurrent animations, and it might be worth revisiting now. If you'd like to take a shot at it, please feel free!

**Comment by BruceJohnJennerLawso** [comment] 2015-06-11 16:27
ok, my js experience is a little bit thin, but I might be able to stumble my way through to a solution. Thanks!

**Comment by JulesBlm** [comment] 2018-11-13 22:09
Hi, I've created a pull request that fixes this issue!

**Comment by JulesBlm** [comment] 2021-10-07 19:34
Closed by pull request https://github.com/UW-Macrostrat/geo-timescale/pull/6

**Closed as completed by JulesBlm** 2021-10-07 19:34 UTC
